theme: jekyll-theme-slate

title: [Portfolio & Resume Showcase]
description: [The main purpose of this website is to showcase my current portfolio as well as update any interested user about my 
new adventure in the life of an Application Developer.]
